[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
FloquetExpansions = "3d8c71b5-958b-4b86-b80e-339bb07db863"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
VanVleckRecursion = "b035d78d-16e8-4eee-b57b-0bcdd92a70b5"

[compat]
Documenter = "1.16.1"
DocumenterTools = "0.1.21"
Literate = "2.21.0"
Plots = "1.41.4"
Term = "1, 2.0"
VanVleckRecursion = "0.1.1"
